---
kind: pipeline
name: validate

trigger:
  branch:
    - master
    - develop
  event:
    exclude:
      - pull_request

steps:
  - name: yamllint
    image: cytopia/yamllint:latest
    commands:
      - yamllint .
  - name: jsonlint
    image: sahsu/docker-jsonlint
    commands:
      - jsonlint --version || true
      - |
        for file in $(find . -type f -name "*.json" -path "mysensors.json" -prune); do
            if ! jsonlint -q $file; then
            export FAILED=1
            else
            echo "$file OK"
            fi
        done
        if [ "${FAILED}" = "1" ]; then
            exit 1
        fi

---
kind: pipeline
name: test

trigger:
  branch:
    - master
    - develop
  event:
    exclude:
      - pull_request

steps:
  - name: stage files
    image: alpine:latest
    commands:
      -  mv fake_secrets.yaml secrets.yaml
  - name: hass-latest
    image: homeassistant/home-assistant:latest
    pull: if-not-exists
    commands:
      # - mv fake_secrets.yaml secrets.yaml
      - python -m homeassistant --script check_config --info all --config .
  - name: hass-rc
    image: homeassistant/home-assistant:rc
    pull: if-not-exists
    commands:
      # - mv fake_secrets.yaml secrets.yaml
      - python -m homeassistant --script check_config --info all --config .
  - name: hass-dev
    image: homeassistant/home-assistant:dev
    pull: if-not-exists
    commands:
      # - mv fake_secrets.yaml secrets.yaml
      - python -m homeassistant --script check_config --info all --config .

---
kind: pipeline
name: upgrade

depends_on:
  - validate
  - test

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request

steps:
  - name: upgrade to hass-latest
    image: appleboy/drone-ssh
    settings:
      host:
        - '172.16.40.20'
      username: root
      key:
        from_secret: ssh_key
      port: 22
      script:
        - source '/etc/profile.d/homeassistant.sh' # <-- https://github.com/hassio-addons/addon-ssh/issues/115
        - echo "Updating Home Assistant Core"
        - echo "current core is $(ha core info | grep ^version:)"
        - ha core update
        - echo "updated core is $(ha core info | grep ^version:)"
        - echo "Updating Home Assistant Supervisor"
        - echo "current supervisor is $(ha supervisor info | grep ^version:)"
        - ha supervisor update
        - echo "updated supervisor is $(ha supervisor info | grep ^version:)"

---
kind: pipeline
name: deploy

depends_on:
  - validate
  - test
  - upgrade

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request

steps:
  - name: git pull
    image: appleboy/drone-ssh
    settings:
      host:
        - '172.16.40.20'
      username: root
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd ~/config
        - git fetch
        - git reset --hard origin/master

  - name: restart
    image: appleboy/drone-ssh
    settings:
      host:
        - '172.16.40.20'
      username: root
      key:
        from_secret: ssh_key
      port: 22
      script:
        - source '/etc/profile.d/homeassistant.sh' # <-- https://github.com/hassio-addons/addon-ssh/issues/115
        - echo "restarting home assistant"
        - ha core restart

#! - re-generate signature if changed via `drone sign jinkang23/Home-AssistantConfig --save`
---
kind: signature
hmac: e992f5fc8b1de1817d553e2303ffe26d7584f80b06450358b1137504e2184ae1

...
