---
kind: pipeline
name: validate

steps:
  - name: yamllint
    image: cytopia/yamllint:latest
    commands:
      - yamllint .
    # failure: ignore
  - name: jsonlint
    image: sahsu/docker-jsonlint
    commands:
      - jsonlint --version || true
      - |
        for file in $(find . -type f -name "*.json" -path "mysensors.json" -prune); do
            if ! jsonlint -q $file; then
            export FAILED=1
            else
            echo "$file OK"
            fi
        done
        if [ "${FAILED}" = "1" ]; then
            exit 1
        fi
    # failure: ignore

---
kind: pipeline
name: test
# depends_on:
#   - validate

steps:
  - name: stage files
    image: alpine:latest
    commands:
      -  mv fake_secrets.yaml secrets.yaml
  - name: ha-latest
    image: homeassistant/home-assistant:latest
    pull: if-not-exists
    commands:
      # - mv fake_secrets.yaml secrets.yaml
      - python -m homeassistant --script check_config --info all --config .
  - name: ha-rc
    image: homeassistant/home-assistant:rc
    pull: if-not-exists
    commands:
      # - mv fake_secrets.yaml secrets.yaml
      - python -m homeassistant --script check_config --info all --config .
  - name: ha-dev
    image: homeassistant/home-assistant:dev
    pull: if-not-exists
    commands:
      # - mv fake_secrets.yaml secrets.yaml
      - python -m homeassistant --script check_config --info all --config .

---
kind: pipeline
name: upgrade

depends_on:
  - validate
  - test

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request

steps:
  - name: upgrade to ha-latest
    image: appleboy/drone-ssh
    settings:
      host:
        - 'hass.i.hs2k.us'
      username: root
      key:
        from_secret: ssh_key
      port: 22
      script:
        - echo "Updating Home Assistant Core"
        - echo "current core version is $(ha core info | grep ^version:)"
        - ha core update
        - echo "updated core version is $(ha core info | grep ^version:)"
        - echo "Updating Home Assistant Supervisor"
        - echo "current supervisor version is $(ha supervisor info | grep ^version:)"
        - ha supervisor update
        - echo "updated supervisor version is $(ha supervisor info | grep ^version:)"

---
kind: pipeline
name: deploy

depends_on:
  - validate
  - test
  - upgrade

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request

steps:
  - name: git pull
    image: appleboy/drone-ssh
    settings:
      host:
        - 'hass.i.hs2k.us'
      username: root
      key:
        from_secret: ssh_key
      port: 22
      script:
        - cd ~/config
        - git fetch
        - git reset --hard origin/master

  - name: restart
    image: appleboy/drone-ssh
    settings:
      host:
        - 'hass.i.hs2k.us'
      username: root
      key:
        from_secret: ssh_key
      port: 22
      script:
        - echo "restarting home assistant"
        - ha core restart || true
