
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Includes
automation: !include_dir_merge_list automation
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
