
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: America/Chicago

  customize: !include customize.yaml

# Text to speech
tts:
  - platform: google_translate

# Includes
automation: !include_dir_merge_list automation
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# *** Integrations *** #
homekit:

# ***Custom Components*** #

# alarmdotcomajax: https://github.com/uvjustin/alarmdotcomajax
alarm_control_panel:
  - platform: alarmdotcomajax
    username: !secret alarmdotcom_username
    password: !secret alarmdotcom_password
    code: !secret alarmdotcom_code
    force_bypass: "true"
    no_entry_delay: "home"
    silent_arming: "false"
