
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: America/Chicago
  external_url: !secret ha_external_url
  internal_url: !secret ha_internal_url
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
      trusted_networks:
        - 172.16.1.0/24

# integrations
# https://www.home-assistant.io/integrations/google_assistant
google_assistant:
  project_id: !secret ga_project_id
  # service_account: !include SERVICE_ACCOUNT.JSON
  # report_state: true
  # exposed_domains:
  #   - switch
  #   - light
  # entity_config:
  #   switch.kitchen:
  #     name: CUSTOM_NAME_FOR_GOOGLE_ASSISTANT
  #     aliases:
  #       - BRIGHT_LIGHTS
  #       - ENTRY_LIGHTS
  #   light.living_room:
  #     expose: false
  #     room: LIVING_ROOM

cloud:
ios:

# Text to speech
tts:
  - platform: google_translate

# https://www.home-assistant.io/integrations/http
http:
  server_host: '0.0.0.0'
  use_x_forwarded_for: true
  trusted_proxies:
    - '172.16.1.1'

# Includes
automation: !include_dir_merge_list automation
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# *** Integrations *** #
homekit:
  auto_start: false

# ***Custom Components*** #

# alarmdotcomajax: https://github.com/uvjustin/alarmdotcomajax
alarm_control_panel:
  - platform: alarmdotcomajax
    username: !secret alarmdotcom_username
    password: !secret alarmdotcom_password
    code: !secret alarmdotcom_code
    force_bypass: "true"
    no_entry_delay: "home"
    silent_arming: "false"
