
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Home
  latitude: !secret ha_latitude
  longitude: !secret ha_longitude
  elevation: !secret ha_elevation
  unit_system: imperial
  time_zone: America/Chicago

  customize: !include customize.yaml

# zwave:
#   usb_path: /dev/ttyACM0
#   config_path: /config/ozw_config


# customize: !include customize.yaml
# customize_domain:
#   automation:
#     initial_state: 'on'

# whitelist_external_dirs:
#   - /config/www

# http:
#   base_url: !secret ha_base_url
#   server_port: 443
#   ssl_certificate: /ssl/fullchain.pem
#   ssl_key: /ssl/privkey.pem

#lovelace:
#  mode: yaml

# Text to speech
tts:
  - platform: google_translate

# Includes
automation: !include_dir_merge_list automation
group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
