# Light groups
- platform: group
  name: kitchen Lights
  entities:
    - light.kitchen_light_level
    - light.dining_room_light_level_2
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_lamp
    - switch.living_room_light_switch
    - light.fireplace_light_level
- platform: group
  name: Master Bedroom Lights
  entities:
    - light.master_bedroom_light_level
    - switch.giraffe_on_off
    - switch.tiger_a47f7bfe_on_off
- platform: group
  name: Outdoor Lights
  entities:
    - switch.porch_light_switch_2
    - switch.patio_light_switch_4
- platform: group
  name: Library Lights
  entities:
    - switch.library_lamp_18b97afe_on_off
    - switch.library_light_switch
- platform: group
  name: Misc Lights
  entities:
    - light.entryway_light_level_3
    - switch.hallway_light_switch_2
    - switch.laundry_room_light_switch
