# Convert Switches to Lights
- platform: switch
  name: Living Room Light
  entity_id: switch.living_room_light_switch
- platform: switch
  name: Giraffe Lamp
  entity_id: switch.giraffe_on_off
- platform: switch
  name: Tiger Lamp
  entity_id: switch.tiger_on_off
- platform: switch
  name: Patio Light
  entity_id: switch.patio_light_switch
- platform: switch
  name: Porch Light
  entity_id: switch.porch_light_switch
- platform: switch
  name: Library Lamp
  entity_id: switch.library_lamp_on_off
- platform: switch
  name: Library Light
  entity_id: switch.library_light_switch
- platform: switch
  name: Hallway Light
  entity_id: switch.hallway_light_switch
- platform: switch
  name: Laundry Room Light
  entity_id: switch.laundry_room_light_switch


# Light groups
- platform: group
  name: kitchen Lights
  entities:
    - light.kitchen_light_level
    - light.dining_room_light_level
- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_lamp
    - light.living_room_light
    - light.fireplace_light_level
    - light.grandma_s_lamp
- platform: group
  name: Master Bedroom Lights
  entities:
    - light.master_bedroom_light_level
    - light.giraffe_lamp
    - light.tiger_lamp
- platform: group
  name: Outdoor Lights
  entities:
    - light.porch_light
    - light.patio_light
- platform: group
  name: Library Lights
  entities:
    - light.library_lamp
    - light.library_light
- platform: group
  name: Misc Lights
  entities:
    - light.entryway_light_level
    - light.hallway_light
    - light.laundry_room_light
- platform: group
  name: All Inside Lights
  entities:
    - light.kitchen_light_level
    - light.dining_room_light_level
    - light.living_room_lamp
    - light.living_room_light
    - light.fireplace_light_level
    - light.grandma_s_lamp
    - light.master_bedroom_light_level
    - light.giraffe_lamp
    - light.tiger_lamp
    - light.library_lamp
    - light.library_light
    - light.entryway_light_level
    - light.hallway_light
    - light.laundry_room_light
