- platform: mqtt
  name: ozw_network_ready
  state_topic: OpenZWave/1/status/
  value_template: >
    {{ "on" if value_json.Status in ["driverAwakeNodesQueried", "driverAllNodesQueriedSomeDead", "driverAllNodesQueried"] else "off" }}
  json_attributes_topic: OpenZWave/1/status/
  device_class: "connectivity"
