- platform: mqtt
  name: ozwd_available
  state_topic: OpenZWave/1/status/
  value_template: >
    {{ "ON" if value_json.Status in ["driverAwakeNodesQueried", "driverAllNodesQueriedSomeDead", "driverAllNodesQueried"] else "OFF" }}
  json_attributes_topic: OpenZWave/1/status/
  device_class: "connectivity"
