- alias: Create All Lights Group on Startup
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: python_script.create_all_group
      data:
        domain: light
        group: all_lights
