- alias: "System - Let's Encrypt Renewal"
  trigger:
    platform: time
    at: '01:25:00'
  action:
    - service: hassio.addon_restart
      data:
        addon: core_letsencrypt
# - alias: 'Start HomeKit'
#   trigger:
#     - platform: event
#       event_type: zwave.network_ready
#     - platform: event
#       event_type: zwave.network_complete
#     - platform: event
#       event_type: zwave.network_complete_some_dead
#   action:
#     - service: homekit.start
- alias: 'Start HomeKit'
  trigger:
    - platform: state
      entity_id: sensor.ozw_status
      to: 'driverAllNodesQueried'
    - platform: state
      entity_id: sensor.ozw_status
      to: 'driverAwakeNodesQueried'
    - platform: state
      entity_id: sensor.ozw_status
      to: 'driverAllNodesQueriedSomeDead'
  action:
    - service: homekit.start
