- alias: "System - Let's Encrypt Renewal"
  trigger:
    platform: time
    at: '01:25:00'
  action:
    - service: hassio.addon_restart
      data:
        addon: core_letsencrypt
- alias: 'Start HomeKit'
  trigger:
    - platform: state
      entity_id: binary_sensor.ozw_network_ready
      to: 'on'
  action:
    - service: homekit.start
